disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Marcus Rasmussen"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"

["params.author"]
name = "Marcus Rasmussen"
headline = false
